feat: #26/ 지점 상세 페이지 구현 및 타입 수정
4-frame-photos-map/frontend pull request #33
Opened 2023-03-31 12:20 UTC by GeonwooShin

## 🛠 작업 내용

close #26 

- 카카오 맵 연결 완료했습니다.
- 지점 상세 페이지 구현을 완료했습니다. 
- 렌더링 시 데이터 페칭에 걸리는 시간 때문에 깜박거리는 현상 해결하기 위해 ssr이용해서 구현했습니다.
- 리뷰 아이템 컴포넌트 작성했습니다.
- 깃북에 업데이트 된 사항으로 전체적으로 타입 수정을 완료했고, api 리턴 값을 result로 수정했습니다.

----수정----

useQuery custom hook을 구현했습니다.
getServerSideProps 내에서 prefetch를 통한 hydrate 방식으로 변경했습니다.
kakao 콜백 페이지 내에서 return 파라미터를 수정했습니다.

## 📸 스크린샷 or GIF

![스크린샷 2023-03-31 오후 8 43 10](https://user-images.githubusercontent.com/79186378/229118247-53f6db0f-3b0f-468e-adb9-fcbe8c1282c0.png)

2023-03-31 17:45 UTC, thyeone approved these changes
고생하셨습니다!👍 머지 후 해당 코드 반영해서 PR 올리겠습니다!

2023-03-31 18:41 UTC, thyeone commented on src/pages/shopDetail/index.tsx
> +}
SSR에 대해서도 이처럼 타입을 지정하는 게 좋아보입니다!

```javascript
export async const getServerSideProps: GetServerSideProps<ShopDetail[]>({ ctx }) {
  const res = shopApi.getShopDetail(query.shopId, query.distance);
  return { props: res };
}
```
처럼 타입을 지정하고 파라미터로 넘겨받을 때도 
```javascript
const ShopDetail = (props: ShopDetail) => {
...
}
```
`getServerSideProps` 부분에도 타입을 명시해주어야 하는 이유는 `getServerSideProps` 함수를 참조하여 파라미터 값의 타입을 추론할 수 있어 보다 안전하게 사용할 수 있다고 하네요!

2023-03-31 19:01 UTC, thyeone commented on src/apis/favorite/favorite.d.ts
>  };
다른 API는 확인하지는 못했는데, 찜과 관련된 속성은 
```json
{
    "success": true,
    "message": "찜 목록 조회 성공",
    "result": [
        {
            "id": 8,
            "shop": {
                "id": 3040,
                "place_name": "하루필름",
                "road_address_name": "서울 용산구 이태원로26길 16"
            }
        },
       ]
}
```

으로 수정이 된 거 같아요! 다른 API도 확인 후 수정 부탁드리겠습니다

2023-03-31 19:02 UTC, thyeone requested changes

2023-03-31 19:02 UTC, thyeone commented on src/apis/favorite/favorite.d.ts
>  };
다른 API는 확인하지는 못했는데, 찜과 관련된 속성은
```json
{
    "success": true,
    "message": "찜 목록 조회 성공",
    "result": [
        {
            "id": 8,
            "shop": {
                "id": 3040,
                "place_name": "하루필름",
                "road_address_name": "서울 용산구 이태원로26길 16"
            }
        },
       ]
}
```
으로 수정이 된 거 같아요! 다른 API도 확인 후 수정 부탁드리겠습니다

2023-03-31 19:12 UTC, thyeone commented on src/pages/shopDetail/index.tsx
> +}
그리고 추후에 `useQuery`문 작성해서 수정하는 게 어떠실까요?

2023-03-31 19:24 UTC, thyeone commented on src/apis/shop/shopApi.ts
getShopsInRad에서 brd를 옵셔널로 수정하셔아 할 것 같습니다!

2023-04-01 05:41 UTC, GeonwooShin commented on src/apis/shop/shopApi.ts
깃북에 명시되어 있는대로 옵셔널 파라미터 수정했습니다👍

2023-04-01 05:44 UTC, GeonwooShin commented on src/apis/favorite/favorite.d.ts
>  };
넵 수정했습니다!

2023-04-01 05:44 UTC, GeonwooShin commented on src/pages/shopDetail/index.tsx
> +}
타입 지정 피드백 감사합니다!

useQuery문 작성하자는 건 getServerSideProps 내에서 useQuery 훅을 사용하자는 말씀이실까요?

2023-04-01 06:08 UTC, thyeone commented on src/pages/shopDetail/index.tsx
> +}
네 맞습니다! 훅은 따로 폴더를 분리해서 사용하는 게 좋을 거 같아요

2023-04-01 06:08 UTC, thyeone approved these changes
확인했습니다!!👍

2023-04-01 06:21 UTC, GeonwooShin commented on src/pages/shopDetail/index.tsx
> +}
getServerSideProps 함수 내에서는 useQuery hook은 사용할수 없습니다

2023-04-01 06:42 UTC, thyeone commented on src/pages/shopDetail/index.tsx
> +}
https://tesseractjh.tistory.com/269 참고해주시겠어요?!

2023-04-01 06:46 UTC, GeonwooShin commented on src/pages/shopDetail/index.tsx
> +}
제가 아까 말씀드린 useQuery 훅은 custom hook을 말씀드린겁니다!

2023-04-01 07:10 UTC, thyeone commented on src/pages/shopDetail/index.tsx
> +}
아, 제가 잘못 말씀드린 거 같아요
react-query의 커스텀훅은 getServerSideProps()의 외부에서 정의하고 내부에서는 queryClient를 생성하자는 말이였습니다!

2023-04-01 08:18 UTC, merged